version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile_dev
    container_name: djando_news_dev
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python ./manage.py runserver 0.0.0.0:8000"
    volumes: 
      - "./project:/app"
    ports:
      - "8000:8000"

  celery:
    volumes:
      - "./project:/app"

  celery-beat:
    volumes:
      - "./project:/app"

  php-redis-admin:
    image: faktiva/php-redis-admin
    container_name: pra
    environment:
      - PHPREDMIN_DATABASE_REDIS_0_HOST=redis
    ports:
      - "8080:80"
    depends_on:
      - "redis"

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=qwerty
    ports:
    - "8888:80"
    depends_on:
    - "db"