version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    container_name: djando_news
    depends_on:
      - "db"
    environment:
      DATABASE_URL: "postgres://postgres@db/postgres"

  db:
    container_name: djando_news_db
    image: "postgres:latest"